mklink /D E:\Documents\share\Movie 	"\\nas.toru.local\NAS_Main\Backup\Download\Movie"
mklink /D E:\Documents\share\Picture 	"\\nas.toru.local\NAS_Main\Backup\Backup\Picture"
mklink /D E:\Documents\share\Music 	"\\nas.toru.local\NAS_Main\Backup\Download\My Music"
mklink /D E:\Documents\share\Documents 	"\\nas.toru.local\NAS_Main\Backup\Backup\Document"
mklink /D E:\Documents\share\Dojin 	"\\nas.toru.local\NAS_Main\Backup\Download\Doujin"
mklink /D E:\Documents\share\Freesoft 	"\\nas.toru.local\NAS_Main\Backup\Backup\Freesoft"
set /P USR_INPUT_STR="Please type any key to exit this script : "
