mklink /D E:\Documents\share\Movie 	"\\192.168.100.2\homes\toru\Backup\Download\Movie"
mklink /D E:\Documents\share\Picture 	"\\192.168.100.2\homes\toru\Backup\Backup\Picture"
mklink /D E:\Documents\share\Music 	"\\192.168.100.2\homes\toru\Backup\Download\My Music"
mklink /D E:\Documents\share\Documents 	"\\192.168.100.2\homes\toru\Backup\Backup\Document"
mklink /D E:\Documents\share\Dojin 	"\\192.168.100.2\homes\toru\Backup\Download\Doujin"
mklink /D E:\Documents\share\Freesoft 	"\\192.168.100.2\homes\toru\Backup\Backup\Freesoft"
set /P USR_INPUT_STR="Please type any key to exit this script : "
